---
title: "PracComp Final Presentation"
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
  pdf_document: default
---

```{r}
#install.packages(c("car","rcompanion","lsmeans"))
```

# WRC Plant Diversity Data (stem counts from 2004 & 2013)

## Importing Data

```{r}
data2004 <- as.data.frame(read.csv("6200_Fall2022/2004_WRCData.csv", header = T))
                          
data2013 <- as.data.frame(read.csv("6200_Fall2022/2013_WRCData.csv", header = T))

library(car)
```

```{r}
head(data2004)
# data2004 is all of the analyzed stem count data (N Species & N Individuals) and Sharron-Wiener Index (H', Hmax, EH) separated by treatment (X) for the year 2004
```
```{r}
head(data2013)
# data2013 is all of the analyzed stem count data (N Species & N Individuals) and Sharron-Wiener Index (H', Hmax, EH) separated by treatment (X) for the year 2013
```

```{r}
species.data <- read.csv("6200_Fall2022/Final Proj Data Revized.csv")
```

```{r}
head(species.data)
#species.data holds the mean stem count of N species for 2004 & 2013 separated by treatment
```

```{r}
indi.data <- read.csv("6200_Fall2022/Final Proj Data Additional.csv")
```

```{r}
head(indi.data)
# indi.data holds the mean stem count of N Individuals for 2004 & 2013 separated by treatment
```

## Graphing

```{r}
library(ggplot2)
```

### N Species
```{r}
NSpecies_2004_2013 <- ggplot(data=species.data, mapping=aes(x=Year, y=Mean, by= Treatment, color= Treatment)) + geom_line() +
  geom_point(shape=15)
```

```{r}
NSpecies_2004_2013
#Mean N Species Stem Count - This graph represents the mean number of species (N Species) from the sampled quadrants separated by treatment in the years 2004 and 2013
```

### N Individuals
```{r}
NIndiv_2004_2013 <- ggplot(data=indi.data, mapping=aes(x=Year, y=Mean, by= Treatment, color= Treatment)) + geom_line() +
  geom_point(shape=15)
```

```{r}
NIndiv_2004_2013
# Mean N Individuals Stem Count - This graph represents the mean stem count of all species (N Individuals) from the sampled quadrants separated by treatment in the years 2004 and 2013. 
```
### Saving Graphs
```{r}
ggsave(filename = "NSpecies_2004_2013.png", plot = NSpecies_2004_2013, width = 24, height = 40, dpi = 300, units = "cm")
```


```{r}
pdf(file = "NSpecies_2004_2013.pdf", width = 24, height = 40)
plot(NSpecies_2004_2013)
dev.off()
```

```{r}
ggsave(filename = "NIndiv_2004_2013.png", plot = NIndiv_2004_2013, width = 24, height = 40, dpi = 300, units = "cm")
```

```{r}
pdf(file = "NIndiv_2004_2013.pdf", width = 24, height = 40)
plot(NIndiv_2004_2013)
dev.off()
```

## Statistics

### Summaries (2004 & 2013)
```{r}
summary(data2004)
# 2004 Data summary – The number of species that grew a stem (N Species). The total number of stems grown, aka Stem Count (N Individuals). The Shannon-Wiener index of diversity (H’). The maximum value possible for a community with any number of species and equal abundance (Hmax). A numerical value for species evenness (EH) 
```
  
```{r}
summary(data2013)
# 2013 Data summary – The number of species that grew a stem (N Species). The total number of stems grown, aka Stem Count (N Individuals). The Shannon-Wiener index of diversity (H’). The maximum value possible for a community with any number of species and equal abundance (Hmax). A numerical value for species evenness (EH)
```
  
### T-Test (2004 & 2013)

#### T-Test on N Species in 2004
```{r}
t.test(data2004$N.species)
# One Sample T-Test results on the number of plant species for the year 2004
```

#### T-Test on N Species in 2013
```{r}
t.test(data2013$N.species)
# One Sample T-Test results on the number of plant species for the year 2013
```

#### T-Test on N Individuals in 2004
```{r}
t.test(data2004$N.individuals)
# One Sample T-Test results on the number of individual stems only for the year 2004
```

#### T-Test on N Individuals in 2013
```{r}
t.test(data2013$N.individuals)
# One Sample T-Test results on the number of individual stems only for the year 2013
```



